### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by fabianPas** [obsidianproject/MessengerAndroid#1]
I don't receive any notifications when I receive messages. I have a OnePlus 3T with Android 8.0.0 and Oxygen OS 5.0.

**Comment by netsfx** [comment]
not implemented yet!

**Comment by Manbearpixel** [comment]
+1

Customisable notification setting

**Comment by netsfx** [comment]
noted (and in progress), see here:
https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
