### ISSUE TITLE
Enhancement: Make it possible to unlock app with fingerprint

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/MessengerAndroid#10]
Alway typing in a strong password for unlockin the app is painfull.
It would be much nicer if you could enable the option to use your fingerprint to unlock the app. I dont know if this is possible regarding security and privacy, but would be nice to have.

**Comment by Manbearpixel** [comment]
+1

**Comment by netsfx** [comment]
that could be an optional setting, noted here:
https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
