### ISSUE TITLE
Bug: Malformed text

### ISSUE THREAD

**Issue by Manbearpixel** [obsidianproject/MessengerAndroid#11]
## Backup email subject line
"Obsidian Indentity Bckup"

## Missing letter "encrypted"
![missing letter](https://cdn.discordapp.com/attachments/383322983042646026/394561424157966347/Screenshot_20171224-124558.png)

## Missing letter "your"
![missing letter](https://cdn.discordapp.com/attachments/383322983042646026/394563358688280576/Screenshot_20171224-125337.png)

**Comment by daniilrybin** [comment]
fixed
