### ISSUE TITLE
Remove Lorem Ipsums

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/MessengerAndroid#12]
The current release has some lorem ipsum texts in the privacy settings. Users are getting confused when seeing them. You should remove them and just alert a "currently not implemented" when users attempt to click on the privacy settings.

**Comment by netsfx** [comment]
Bei den Settings/Klappmenü, alles was "Not Implemented" ist, stattdessen 'ausgrauen', wie bei deaktivierten Buttons.

**Comment by netsfx** [comment]
Auf der eigentlichen Settings-Seite alles außer About Obsidian im Source code auskommentieren.

**Comment by netsfx** [comment]
done
