### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hugokx** [obsidianproject/MessengerAndroid#13]
The app won't install on my phone 
LG G3 (D855)
Android 4.4.2
Kernel 3.4.0
Error "There is a problem parsing the package"

**Comment by Manbearpixel** [comment]
I believe it seems like the minimum supported Android version is 5 due to cryptographic libraries or processing power.

**Comment by netsfx** [comment]
Yes, Android 5 is minimum atm. We have to discuss if it makes sense to support 4.x.

**Comment by hugokx** [comment]
Well as of December 2017  there are still 13.4% of users on Android 4.4 at least. Does that mean that 1 user out of ten won't be able to use OSM ?

[Stat android version market share](https://fossbytes.com/most-popular-android-versions-always-updated/)

Sorry for not upgrading to android 5.0 and being an oldie! My phone is still a beast in terms of computer power so I don't see the point.

**Comment by netsfx** [comment]
noted, see also here:
https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
