### ISSUE TITLE
Random Messages disappeared 

### ISSUE THREAD

**Issue by Cryptowell** [obsidianproject/MessengerAndroid#15]
Galaxy S7 - in every conversation I have had (8 different users) some of the message bubbles are empty but tge bubbles are still there with the time stamp visible. It's like they were deleted automatically but the bubble doesn't disappear and the time stamp is still showing on that particular bubble.

**Comment by Hein-Bloed** [comment]
I also have this on my OnePlus 2

**Comment by ineeve** [comment]
I have noticed that if you wait some time the text will eventually turn visible.

**Comment by netsfx** [comment]
yes, first, per message, a bubble is put on the thread. Then, decryption of the contents of the bubble starts. Apparently, this can be very slow at times, so that the bubbles appear empty. We have to investigate, why decryption takes so long.

**Comment by daniilrybin** [comment]
fixed
