### ISSUE TITLE
A couple of issues..

### ISSUE THREAD

**Issue by Pleistocene666** [obsidianproject/MessengerAndroid#16]
First of all, I want to say that I really like the project and that I think the app is awesome, albeit there are some flaws (in my opinion)....

1. It should be possible to attach names to codes. Let's say that you have 15-20 friends on the app.. You need to be able to distinguish between them, else you'll have to look through god knows how many convos/codes before you find the one you're looking for.

2. If it's possible, make an integrated keyboard within the app, where the dictionary is encrypted and only works with the specific account you've created (personal) - which of course will get deleted if you delete that account/user. It's frustrating that there's no dictionary. Takes a long time to type.

3. I had to connect to the internet via my WLAN connection at home before I could get it working.. Probably some port issue.. That kind of kills the whole idea of a mobile app, since you'd have to be at home before it's working. It needs to work with mobile internet, 4G or whatever.. I've noticed that other people in the discord chat had the same problem. So you might want to have a look at it. 

4. When you set up a new account/user and type in a new password, it keeps saying that the password is weak. You literally need to type in 30-40 characters (both small and capital letters), numbers and signs before it stops saying that it's weak.. In my opinion, it should be enough with 15-18 characters before it stops saying "weak password".. No one wants to have to type in that many characters every time, and people might find it necessary as they're just doing what they're told. Maybe you could make a PIM along with a shorter password.. Much like VeraCrypt has PIMs. And even maybe implement a bit of PoW in the decryption process? - That'd make it easier for people to log in, and probably also a lot safer. Most smartphones nowadays are pretty powerful, so a bit of PoW shouldn't be a problem.

5. Make the app log off/shut down everytime you exit it. If it's open constantly without the users manually closing it, and their phone is seized while the app is open on their phone, the authorities will be able to read the recent conversations by simply opening the app, which kills the purpose of it. 

6. I have an old phone with android 4.X that I tried to install it on too, and it keeps giving me parsing error when I try to install the app.. Would be nice if it worked with more or less all android versions.

Cheers! And merry christmas!

**Comment by ineeve** [comment]
In regards to 1: You can already attach names to codes by clicking in the image of your contact.

**Comment by netsfx** [comment]
1. yes, done!
2. no dictionary!
3. Works on WiFi and mobile data normally, bug reports require more information.
4. You can set a password as shot as you like, and it is already protected with 'PoW'. Still, with a less then 256 Bit password (after transformation), the password is less good then the AES 256 Bit protection would offer. That's the sad truth! ;-)
5. Yes, fast and frequent exit is good, we'll go in that direction.
6. 4.x is not supported to avoid AppCompat bloat.
