### ISSUE TITLE
Enhancement: Allow broadcasting of messages

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/MessengerAndroid#18]
If you would be able to send messages to everybody having your OSM-ID, things such as channels would be possible. People could subscribe to one OSM-ID and get all messenges the OSM-ID posts. This way we could provide things like news channels for example. Those channels should be unidirectional imo. I currently cannot know how the internals of the OSM are working, so I cannot know if this is possible. Feel free to close if its not possible.

**Comment by netsfx** [comment]
moved to:
https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
