### ISSUE TITLE
Enhancement: Add Tor support

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/MessengerAndroid#19]
To enable truly anon comunication, it would help if connections of the app are routed via tor.
This could be done using Orbot and [NetCipher](https://github.com/guardianproject/netcipher).
Connecting over Tor should be optional and not the default imo, because it slows down the connection.

**Comment by netsfx** [comment]
agreed, that's a great feature!

**Comment by netsfx** [comment]
We need to put that on the backlog until we have normal connections more stable. And yes, an option in the settings would be nice.

**Comment by netsfx** [comment]
moved to: https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
