### ISSUE TITLE
Copying of OSM ID

### ISSUE THREAD

**Issue by fabianPas** [obsidianproject/MessengerAndroid#2]
Currently it doesn't seem possible to easily copy your OSM ID from the app. It would be nice to be able to copy this easily to share this with friends, colleagues etc.

**Comment by Hein-Bloed** [comment]
Would be nice if we also can also easily get the OSM ID as a qrcode

**Comment by netsfx** [comment]
@Hein-Bloed for the QR code, do you mean the situation when you are sitting next to someone else and want to pass on the ID?

**Comment by Hein-Bloed** [comment]
@netsfx exactly this. it would be nice if we can show the QR code, and the other person has a integrated QR code scanner in the OSM which can easily read and import the OSM-ID.
This way you dont have to share your OSM ID in other chats and you can remain anonym.

**Comment by netsfx** [comment]
> This way you dont have to share your OSM ID in other chats and you can remain anonym.
Very good point!!

Also, the other's public key can be probably validated then. So, the QR code should not contain the ID only, but the full public key.

**Comment by Manbearpixel** [comment]
More scenarios:
- QR sticker in public
- QR code on website
- QR code on card

+1 on the QR feature request

**Comment by netsfx** [comment]
Simple copying of own ID is now possible, QR Code feature noted here:
https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
