### ISSUE TITLE
Enhancement: Multi-Identity accounts 

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/MessengerAndroid#23]
It would be a nice feature if the user is able to use different ids in the app. This way one user could use different identitys and switch between them inside the app, without reinstalling or resetting the app. This enhances privacy, because users can give different people different IDs. Also things like a private ID and a buissness ID are possible.

**Comment by netsfx** [comment]
I think that's a great idea! Definitely worth considering after v1.0!

**Comment by netsfx** [comment]
see https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger/
