### ISSUE TITLE
Only the last ten messages can be seen in a chat

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/MessengerAndroid#5]
When you write with a contact, you can only scroll back to the last 10 messages.
Older messages cannot be seen anymore. If this is a security feature and older messages are deleted, it would be nice if we can adjust the number of messages after which the old messages are getting deleted.
If this is simply a bug this could be a feature in the future.

**Comment by Hein-Bloed** [comment]
#4 is the same bug

**Comment by netsfx** [comment]
It's a bug :-)

**Comment by daniilrybin** [comment]
fixed
