### ISSUE TITLE
Swype keyboard  - user feedback needed

### ISSUE THREAD

**Issue by netsfx** [obsidianproject/MessengerAndroid#6]

**Comment by netsfx** [comment]
Can somebody elaborate what is expected here? Swype - so you install a non-standard keyboard on Android, and you expect that keyboard comes up in the app? Can someone provide a link to that keyboad package so that we can test?

**Comment by Manbearpixel** [comment]
Swype Keyboard for Android (Free Version)
https://play.google.com/store/apps/details?id=com.nuance.swype.trial&hl=en

**Comment by Manbearpixel** [comment]
```custom-keyboard.feature
As   a user
And  I have Swype (or third-party) keyboard installed
And  I have it set as my default keyboard
When I open OSM
And  I click the message input box to begin typing
Then I should be able to use Swype (or third-party) as my keyboard
```

**Comment by netsfx** [comment]
noted, see here:
https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
