### ISSUE TITLE
Enhancement: Replace textual message status with symbols

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/MessengerAndroid#7]
Currently the message status is displayed by the words "OnServer", "Dellivered", "Sending" and "Read".The words are often cut in the middle, depending on the size of the message.
It would be better to use whatsapp or telegramm like symbols.
For example: 
"Sending" -> "..."
"OnServer" -> one hook
"Delivered" -> two hooks
"Read" -> two green hooks

**Comment by Manbearpixel** [comment]
+1

**Comment by netsfx** [comment]
noted:
https://github.com/obsidianproject/MessengerAndroid/wiki/Enhancement-Proposals-for-Obsidian-Secure-Anonymous-Messenger
